#cloud-config
users:
  - name: sysadmin
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - gh:<GITHUB_USERNAME>
disable_root: true
hostname: <HOSTNAME>
fqdn: <DOMAIN_NAME>
prefer_fqdn_over_hostname: true
timezone: UTC
power_state:
  mode: reboot
  timeout: 300
package_update: true
package_upgrade: true
packages:
  - htop
  - systemd-container
runcmd:
  # Harden SSH config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
  - sed -i -e '/^X11Forwarding/s/^.*$/X11Forwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#MaxAuthTries/s/^.*$/MaxAuthTries 2/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowTcpForwarding/s/^.*$/AllowTcpForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AllowAgentForwarding/s/^.*$/AllowAgentForwarding no/' /etc/ssh/sshd_config
  - sed -i -e '/^#AuthorizedKeysFile/s/^.*$/AuthorizedKeysFile .ssh\/authorized_keys/' /etc/ssh/sshd_config
  - sed -i '$a AllowUsers sysadmin' /etc/ssh/sshd_config
  # Enable firewall
  - ufw allow OpenSSH
  - ufw allow http
  - ufw allow https
  - ufw enable
  # Install Caddy server
  - apt install -y debian-keyring debian-archive-keyring apt-transport-https
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  - curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list
  - apt update
  - apt install caddy
write_files:
  - path: /etc/caddy/Caddyfile
    permissions: "0644"
    defer: true
    content: |
      {
        email sysadmin@domain.com
      }

      import services/*.Caddyfile
